// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseContact.DatabaseContact;
using DatabaseContact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseContact.DatabaseContact.Configurations
{
    public partial class DebtCalcConfiguration : IEntityTypeConfiguration<DebtCalc>
    {
        public void Configure(EntityTypeBuilder<DebtCalc> entity)
        {
            entity.HasKey(e => e.id).IsClustered(false);

            entity.ToTable("debt_calc", tb => tb.HasTrigger("tr_debt_calc_aiud"));

            entity.HasIndex(e => e.parent_id, "IX_debt_calc_parent_id").IsClustered();

            entity.Property(e => e.NUMBER_VALUE_1).HasComment("Дополнительный параметр число");
            entity.Property(e => e.NUMBER_VALUE_2).HasComment("Дополнительный параметр число");
            entity.Property(e => e.NUMBER_VALUE_3).HasComment("Дополнительный параметр число");
            entity.Property(e => e.NUMBER_VALUE_4).HasComment("Дополнительный параметр число");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DebtCalc> entity);
    }

}
