// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseContact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace DatabaseContact.DatabaseContact.Configurations
{
    public partial class DebtGuarantorConfiguration : IEntityTypeConfiguration<DebtGuarantor>
    {
        public void Configure(EntityTypeBuilder<DebtGuarantor> entity)
        {
            entity.HasKey(e => e.id).HasName("debt_guarantor_PK");

            entity.ToTable("debt_guarantor", tb => tb.HasComment("информация о поручителе по долгу"));

            entity.HasIndex(e => e.parent_id, "IX_D_GUARANTOR_PARENT_ID");

            entity.Property(e => e.id)
                .HasComment("")
                .HasColumnName("id");
            entity.Property(e => e.address)
                .HasMaxLength(256)
                .IsUnicode(false)
                .HasComment("адрес")
                .HasColumnName("address");
            entity.Property(e => e.B_NAME)
                .HasMaxLength(160)
                .IsUnicode(false)
                .HasComment("Банк")
                .HasColumnName("B_NAME");
            entity.Property(e => e.BIK)
                .HasMaxLength(16)
                .IsUnicode(false)
                .HasComment("БИК")
                .HasColumnName("BIK");
            entity.Property(e => e.birth_date)
                .HasComment("Дата рождения")
                .HasColumnType("datetime")
                .HasColumnName("birth_date");
            entity.Property(e => e.birth_place)
                .HasMaxLength(256)
                .IsUnicode(false)
                .HasComment("место рождения")
                .HasColumnName("birth_place");
            entity.Property(e => e.company_name)
                .HasMaxLength(64)
                .IsUnicode(false)
                .HasComment("название компании")
                .HasColumnName("company_name");
            entity.Property(e => e.contract)
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasComment("номер договора")
                .HasColumnName("contract");
            entity.Property(e => e.currency)
                .HasComment("валюта")
                .HasColumnName("currency");
            entity.Property(e => e.DICT_VALUE_1)
                .HasComment("Ссылка на словарь 1 (словарь №261)")
                .HasColumnName("DICT_VALUE_1");
            entity.Property(e => e.director_fio)
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasComment("ФИО ген. директора (юр. лица)")
                .HasColumnName("director_fio");
            entity.Property(e => e.dsc)
                .HasMaxLength(512)
                .IsUnicode(false)
                .HasComment("комментарий")
                .HasColumnName("dsc");
            entity.Property(e => e.education)
                .HasComment("образование (словарь №38)")
                .HasColumnName("education");
            entity.Property(e => e.end_date)
                .HasComment("дата окончания")
                .HasColumnType("datetime")
                .HasColumnName("end_date");
            entity.Property(e => e.ext_id)
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasComment("ID АБС")
                .HasColumnName("ext_id");
            entity.Property(e => e.fair_sum)
                .HasComment("справедливая стоимость")
                .HasColumnType("money")
                .HasColumnName("fair_sum");
            entity.Property(e => e.family_status)
                .HasComment("семейное положение (словарь №1")
                .HasColumnName("family_status");
            entity.Property(e => e.finish_date)
                .HasComment("дата завершения")
                .HasColumnType("datetime")
                .HasColumnName("finish_date");
            entity.Property(e => e.fio)
                .HasMaxLength(1024)
                .IsUnicode(false)
                .HasComment("ФИО")
                .HasColumnName("fio");
            entity.Property(e => e.id_card)
                .HasMaxLength(16)
                .IsUnicode(false)
                .HasComment("Удостоверение личности")
                .HasColumnName("id_card");
            entity.Property(e => e.inn)
                .HasMaxLength(16)
                .IsUnicode(false)
                .HasComment("ИНН")
                .HasColumnName("inn");
            entity.Property(e => e.K_ACCOUNT)
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasComment("Кор. Счет")
                .HasColumnName("K_ACCOUNT");
            entity.Property(e => e.kind).HasColumnName("kind");
            entity.Property(e => e.kpp)
                .HasMaxLength(16)
                .IsUnicode(false)
                .HasComment("Код причины постановки (КПП)")
                .HasColumnName("kpp");
            entity.Property(e => e.liability)
                .HasComment("Тип ответственности (Словарь №")
                .HasColumnName("liability");
            entity.Property(e => e.name)
                .HasMaxLength(256)
                .IsUnicode(false)
                .HasComment("наименование объекта")
                .HasColumnName("name");
            entity.Property(e => e.number_value_1)
                .HasColumnType("money")
                .HasColumnName("number_value_1");
            entity.Property(e => e.OGRN)
                .HasMaxLength(16)
                .IsUnicode(false)
                .HasComment("ОГРН")
                .HasColumnName("OGRN");
            entity.Property(e => e.OKPO)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasComment("ОКПО")
                .HasColumnName("OKPO");
            entity.Property(e => e.OKVED)
                .HasMaxLength(16)
                .IsUnicode(false)
                .HasComment("ОКВЕД")
                .HasColumnName("OKVED");
            entity.Property(e => e.parent_id)
                .HasComment("ссылка на debt")
                .HasColumnName("parent_id");
            entity.Property(e => e.PAS_DOC_TYPE)
                .HasComment("Тип удост. документа (код по словарю №335)")
                .HasColumnName("PAS_DOC_TYPE");
            entity.Property(e => e.PAS_NUMBER)
                .HasMaxLength(120)
                .HasComment("Номер паспорта")
                .HasColumnName("PAS_NUMBER");
            entity.Property(e => e.PAS_PLACE)
                .HasMaxLength(256)
                .HasComment("Место выдачи")
                .HasColumnName("PAS_PLACE");
            entity.Property(e => e.PAS_SERIES)
                .HasMaxLength(80)
                .HasComment("Серия паспорта")
                .HasColumnName("PAS_SERIES");
            entity.Property(e => e.PASS_DT)
                .HasComment("Дата выдачи")
                .HasColumnType("datetime")
                .HasColumnName("PASS_DT");
            entity.Property(e => e.passport)
                .HasMaxLength(1024)
                .IsUnicode(false)
                .HasComment("паспорт")
                .HasColumnName("passport");
            entity.Property(e => e.pay_info)
                .HasMaxLength(256)
                .IsUnicode(false)
                .HasComment("Платежные реквизиты (юр. лица)")
                .HasColumnName("pay_info");
            entity.Property(e => e.position)
                .HasMaxLength(64)
                .IsUnicode(false)
                .HasComment("должность")
                .HasColumnName("position");
            entity.Property(e => e.quality_coeff)
                .HasComment("Коэффициент категории качества")
                .HasColumnName("quality_coeff");
            entity.Property(e => e.R_ACCOUNT)
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasComment("Расчетный счет")
                .HasColumnName("R_ACCOUNT");
            entity.Property(e => e.real_sum)
                .HasComment("рыночная стоимость")
                .HasColumnType("money")
                .HasColumnName("real_sum");
            entity.Property(e => e.sex)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasComment("пол")
                .HasColumnName("sex");
            entity.Property(e => e.social_number)
                .HasMaxLength(16)
                .IsUnicode(false)
                .HasComment("Бизнес-идентификационный номер")
                .HasColumnName("social_number");
            entity.Property(e => e.start_date)
                .HasComment("дата заключения")
                .HasColumnType("datetime")
                .HasColumnName("start_date");
            entity.Property(e => e.string_value_1)
                .HasMaxLength(256)
                .IsUnicode(false)
                .HasColumnName("string_value_1");
            entity.Property(e => e.string_value_2)
                .HasMaxLength(256)
                .IsUnicode(false)
                .HasColumnName("string_value_2");
            entity.Property(e => e.sum)
                .HasComment("залоговая стоимость")
                .HasColumnType("money")
                .HasColumnName("sum");
            entity.Property(e => e.tin)
                .HasMaxLength(16)
                .IsUnicode(false)
                .HasComment("Регистрационный номер налогопл")
                .HasColumnName("tin");
            entity.Property(e => e.typ)
                .HasComment("тип должника (словарь №54)")
                .HasColumnName("typ");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DebtGuarantor> entity);
    }
}
