// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseContact.DatabaseContact;
using DatabaseContact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseContact.DatabaseContact.Configurations
{
    public partial class DocLinkConfiguration : IEntityTypeConfiguration<DocLink>
    {
        public void Configure(EntityTypeBuilder<DocLink> entity)
        {
            entity.HasKey(e => e.id).IsClustered(false);

            entity.ToTable("doc_links", tb => tb.HasTrigger("tr_doc_links_aiu"));

            entity.HasIndex(e => new { e.obj_id, e.r_id }, "IX_doc_links_obj_id&r_id").IsClustered();

            entity.Property(e => e.CHANGE_DT).HasComment("дата последнего изменения");
            entity.Property(e => e.DICT_VALUE_1).HasComment("Техническое поле типа словарь 1");
            entity.Property(e => e.DOC_SIZE).HasComment("размер файла");
            entity.Property(e => e.DT_VALUE_1).HasComment("Техническое поле типа дата 1");
            entity.Property(e => e.EXT_ID).HasComment("Внешний идентификатор");
            entity.Property(e => e.R_CREATE_USER_ID).HasComment("Пользователь, загрузивший документ");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DocLink> entity);
    }
}
