// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseContact.DatabaseContact;
using DatabaseContact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseContact.DatabaseContact.Configurations
{
    public partial class LawActProtokolConfiguration : IEntityTypeConfiguration<LawActProtokol>
    {
        public void Configure(EntityTypeBuilder<LawActProtokol> entity)
        {
            entity.HasKey(e => e.id).HasName("law_act_appel_protokol_PK");

            entity.ToTable("law_act_protokol");

            entity.Property(e => e.ACTION_DT).HasComment("дата действия");
            entity.Property(e => e.REASON).HasComment("причина перевода в текущий статус (словарь 319 - иск/банкротство/правопреемство, 320 - приказ)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LawActProtokol> entity);
    }
}
