// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseContact.DatabaseContact;
using DatabaseContact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseContact.DatabaseContact.Configurations
{
    public partial class LawActSolicitationConfiguration : IEntityTypeConfiguration<LawActSolicitation>
    {
        public void Configure(EntityTypeBuilder<LawActSolicitation> entity)
        {
            entity.ToTable("law_act_solicitation");
            entity.HasKey(e => e.id).HasName("law_act_solicitation_PK");

            entity.Property(e => e.REASON_CODE).HasComment("Причина по словарю 344");
            entity.Property(e => e.REQUEST_SUM).HasComment("Запрошенная сумма");
            entity.Property(e => e.RESULT_SUM).HasComment("Полученная сумма");
            entity.Property(e => e.STATE_ORGAN_ADDRESS).HasComment("Адрес гос.органа");
            entity.Property(e => e.STATE_ORGAN_NAME).HasComment("Название гос.органа");
            entity.Property(e => e.STATE_ORGAN_REQUISITES).HasComment("Реквизиты гос.органа");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LawActSolicitation> entity);
    }
}
