// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseContact.DatabaseContact;
using DatabaseContact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseContact.DatabaseContact.Configurations
{
    public partial class LawActPersonLinkConfiguration : IEntityTypeConfiguration<LawActPersonLink>
    {
        public void Configure(EntityTypeBuilder<LawActPersonLink> entity)
        {

            entity.HasKey(e => e.ID).HasName("pk_law_act_person_link");

            entity.ToTable("LAW_ACT_PERSON_LINK");

            entity.Property(e => e.ID).HasComment("идентификатор записи");
            entity.Property(e => e.LINK_TYPE).HasComment("Тип связи (1-Ответчик/2-Истец/3-Третье лицо)");
            entity.Property(e => e.PERSON_ID).HasComment("Ссылка на физ. или юр. лицо (таблицы person, debt_guarantor)");
            entity.Property(e => e.PERSON_ROLE).HasComment("Роль участника договора в судебном процессе по словарю №235");
            entity.Property(e => e.R_LAW_ACT_ID).HasComment("ID дела");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LawActPersonLink> entity);
    }
}
