// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseContact.DatabaseContact;
using DatabaseContact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseContact.DatabaseContact.Configurations
{
    public partial class LawExecDscLogConfiguration : IEntityTypeConfiguration<LawExecDscLog>
    {
        public void Configure(EntityTypeBuilder<LawExecDscLog> entity)
        {

            entity.HasKey(e => e.id).HasName("PK__law_exec_dsc_log__3528CC84");

            entity.ToTable("law_exec_dsc_log");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LawExecDscLog> entity);
    }
}
