// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseContact.DatabaseContact;
using DatabaseContact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseContact.DatabaseContact.Configurations
{
    public partial class LawExecConfiguration : IEntityTypeConfiguration<LawExec>
    {
        public void Configure(EntityTypeBuilder<LawExec> entity)
        {
            entity.HasKey(e => e.id).HasName("law_exec_PK");

            entity.ToTable("law_exec", tb =>
            {
                tb.HasComment("информация об исполнительном п");
                tb.HasTrigger("tr_law_exec_aiu");
            });

            entity.Property(e => e.id).HasComment("");
            entity.Property(e => e.APPEAL_DATE).HasComment("Дата обжалования");
            entity.Property(e => e.DELIVERY_TYP).HasComment("Способ подачи по словарю №16");
            entity.Property(e => e.DT_VALUE_1).HasComment("Техническое поле типа дата 1");
            entity.Property(e => e.PAUSE_DATE).HasComment("Дата приостановления ИП");
            entity.Property(e => e.PAUSE_REASON).HasComment("Причина приостановления (словарь №266)");
            entity.Property(e => e.QUORUM_ID).HasComment("id запроса в Кворум");
            entity.Property(e => e.REST_SUM).HasComment("остаток по ИД");
            entity.Property(e => e.complete_date).HasComment("Дата получения постановления о");
            entity.Property(e => e.complete_plan_date).HasComment("плановая дата окончания ИП");
            entity.Property(e => e.contract).HasComment("номер договора");
            entity.Property(e => e.court_date).HasComment("дата вынесения");
            entity.Property(e => e.court_doc_num).HasComment("номер исполнительного документ");
            entity.Property(e => e.court_name).HasComment("название суда (устар.)(не испо");
            entity.Property(e => e.currency).HasComment("валюта");
            entity.Property(e => e.deposit_typ).HasComment("наличие залогового имущества");
            entity.Property(e => e.dict_value_1).HasComment("Примечание ИП (Словарь №248)");
            entity.Property(e => e.dsc).HasComment("комментарий");
            entity.Property(e => e.due_sum).HasComment("гос. пошлина");
            entity.Property(e => e.entry_force_dt).HasComment("Дата вступления решения суда в");
            entity.Property(e => e.executive_typ).HasComment("Тип исполнительного документа ");
            entity.Property(e => e.finish_date).HasComment("дата окончания производства");
            entity.Property(e => e.finish_reason).HasComment("причина окончания производства");
            entity.Property(e => e.fssp_date).HasComment("дата сдачи в ФССП");
            entity.Property(e => e.fssp_doc_num).HasComment("номер исполнительного производ");
            entity.Property(e => e.fssp_name).HasComment("название ФССП (устар.)(не испо");
            entity.Property(e => e.fssp_plan_date).HasComment("плановая дата подачи в ФССП");
            entity.Property(e => e.instruct).HasComment("указания руководителя");
            entity.Property(e => e.int_color).HasComment("цвет");
            entity.Property(e => e.load_dt).HasComment("дата загрузки\\формирования ИП");
            entity.Property(e => e.name).HasComment("название продукта");
            entity.Property(e => e.officer_fio).HasComment("ФИО пристава (не используется)");
            entity.Property(e => e.officer_fio2).HasComment("ФИО пристава (зам.) (не исполь");
            entity.Property(e => e.officer_phone).HasComment("телефон пристава (не используе");
            entity.Property(e => e.officer_phone2).HasComment("телефон пристава (зам.) (не ис");
            entity.Property(e => e.officer_room).HasComment("комната пристава (не используе");
            entity.Property(e => e.officer_room2).HasComment("комната пристава (зам.) (не ис");
            entity.Property(e => e.r_act_id).HasComment("ссылка на law_act");
            entity.Property(e => e.r_address_id).HasComment("адрес, по которому на должника");
            entity.Property(e => e.r_court_id).HasComment("ссылка на law_court (ФССП)");
            entity.Property(e => e.r_debt_id).HasComment("ссылка на debt");
            entity.Property(e => e.r_person_id).HasComment("ссылка на person");
            entity.Property(e => e.r_portfolio_id).HasComment("ссылка на portfolio");
            entity.Property(e => e.r_user_id).HasComment("ссылка на users");
            entity.Property(e => e.receipt_act_dt).HasComment("дата получения исп.листа");
            entity.Property(e => e.receipt_arrest_dt).HasComment("дата получения ИП на арест");
            entity.Property(e => e.receipt_recover_dt).HasComment("дата получения ИП на взыскание");
            entity.Property(e => e.reject_date).HasComment("Дата отказа");
            entity.Property(e => e.reject_reason).HasComment("Причина отказа (Словарь №125)");
            entity.Property(e => e.settlement_date).HasComment("дата мирового соглашения");
            entity.Property(e => e.settlement_sum).HasComment("сумма мирового соглашения");
            entity.Property(e => e.start_date).HasComment("дата возбуждения ИП");
            entity.Property(e => e.state).HasComment("статус (словарь №77)");
            entity.Property(e => e.status).HasComment("статус (устар.) (не использует");
            entity.Property(e => e.total_sum).HasComment("общая сумма долга");
            entity.Property(e => e.typ_name).HasComment("тип продукта (ссылка на словар");
            entity.Property(e => e.uncollectibility_act).HasComment("акт о завершении");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LawExec> entity);
    }
}
