// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseContact.DatabaseContact;
using DatabaseContact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseContact.DatabaseContact.Configurations
{
    public partial class LawSessionConfiguration : IEntityTypeConfiguration<LawSession>
    {
        public void Configure(EntityTypeBuilder<LawSession> entity)
        {
            entity.ToTable("law_session");
            entity.Property(e => e.TYP).HasComment("тип судебного заседания (слова");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LawSession> entity);
    }
}
