// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseContact.DatabaseContact;
using DatabaseContact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseContact.DatabaseContact.Configurations
{
    public partial class PersonConfiguration : IEntityTypeConfiguration<Person>
    {
        public void Configure(EntityTypeBuilder<Person> entity)
        {
            entity.HasKey(e => e.id).HasName("person_PK");

            entity.ToTable("person", tb => tb.HasTrigger("tr_person_au"));

            entity.Property(e => e.DEATH_DT).HasComment("Дата смерти");
            entity.Property(e => e.DOCFLOW_DSC).HasComment("комментарий ОД");
            entity.Property(e => e.SNILS).HasComment("СНИЛС");
            entity.Property(e => e.analyst_dsc).HasComment("комментарий аналитика");
            entity.Property(e => e.b_name).HasComment("банк");
            entity.Property(e => e.bik).HasComment("БИК");
            entity.Property(e => e.birth_date).HasComment("дата рождения");
            entity.Property(e => e.birth_place).HasComment("место рождения");
            entity.Property(e => e.company_name).HasComment("название компании");
            entity.Property(e => e.decency).HasComment("порядочность");
            entity.Property(e => e.depart).HasComment("подразделение (soft, hard, exe");
            entity.Property(e => e.director_fio).HasComment("ФИО ген. директора");
            entity.Property(e => e.dsc).HasComment("комментарий");
            entity.Property(e => e.education).HasComment("образование (словарь №38)");
            entity.Property(e => e.email).HasComment("email");
            entity.Property(e => e.f).HasComment("фамилия");
            entity.Property(e => e.family_status).HasComment("семейное положение (словарь №1");
            entity.Property(e => e.flag_workplace_validated).HasComment("Флаг Место работы проверено");
            entity.Property(e => e.i).HasComment("имя");
            entity.Property(e => e.id_).HasComment("ID в главной БД");
            entity.Property(e => e.importance).HasComment("важность персоны");
            entity.Property(e => e.income).HasComment("доход");
            entity.Property(e => e.inn).HasComment("ИНН");
            entity.Property(e => e.k_account).HasComment("кор. счет");
            entity.Property(e => e.kpp).HasComment("КПП");
            entity.Property(e => e.o).HasComment("отчество");
            entity.Property(e => e.ogrn).HasComment("ОГРН");
            entity.Property(e => e.okpo).HasComment("ОКПО");
            entity.Property(e => e.okved).HasComment("ОКВЭД");
            entity.Property(e => e.position).HasComment("должность");
            entity.Property(e => e.r_account).HasComment("расчетный счет");
            entity.Property(e => e.r_passport_id).HasComment("ссылка на паспорт");
            entity.Property(e => e.sex).HasComment("пол");
            entity.Property(e => e.typ).HasComment("тип (1 - физ.лицо, 2 - юр.лицо");
            entity.Property(e => e.website).HasComment("страничка в интернете");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Person> entity);
    }
}
