// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseContact.DatabaseContact;
using DatabaseContact.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DatabaseContact.DatabaseContact.Configurations
{
    public partial class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.HasKey(e => e.id).HasName("users_PK");

            entity.ToTable("users", tb =>
            {
                tb.HasComment("информация о пользователе сист");
                tb.HasTrigger("tr_users_aiu");
            });

            entity.Property(e => e.AGENT_KEY).HasComment("Ключ агента телефонии в JSON с");
            entity.Property(e => e.AGENT_SERVER_TYPE).HasComment("Тип сервера телефонии (словарь");
            entity.Property(e => e.AGENT_TOKEN).HasComment("Токен агента телефонии в JSON ");
            entity.Property(e => e.BLOCK_DT).HasComment("Дата блокировки пользователя ");
            entity.Property(e => e.BLOCK_REASON).HasComment("Причина блокировки пользователя (словарь № 396)");
            entity.Property(e => e.CHANGE_DT).HasComment("дата последнего изменения");
            entity.Property(e => e.DICT_VALUE_1).HasComment(" В новый Combobox подгружать з");
            entity.Property(e => e.EXT_ID_).HasComment("Идентификатор в системе CASEPRO");
            entity.Property(e => e.LANG).HasComment("язык пользователя (словарь 78)");
            entity.Property(e => e.POSITION_CODE).HasComment("Код должности по словарю № 404");
            entity.Property(e => e.R_DEPARTMENT_ID2).HasComment("ссылка на подразделение (depar");
            entity.Property(e => e.agent_id).HasComment("ID Агента (Идентификатор агент");
            entity.Property(e => e.agent_name).HasComment("имя агента");
            entity.Property(e => e.agent_number).HasComment("№ агента СС");
            entity.Property(e => e.agent_pass).HasComment("пароль агента");
            entity.Property(e => e.block_flag).HasComment("признак \"заблокировать логин\"");
            entity.Property(e => e.depart).HasComment("тип (soft или hard)");
            entity.Property(e => e.depart_status).HasComment("0 или NULL, если обычный, 1 - ");
            entity.Property(e => e.dsc).HasComment("комментарий");
            entity.Property(e => e.email).HasComment("электронная почта оператора");
            entity.Property(e => e.emp_number).HasComment("табельный номер");
            entity.Property(e => e.f).HasComment("фамилия");
            entity.Property(e => e.filial).HasComment("филиал. Словарь 61.");
            entity.Property(e => e.finish_work_date).HasComment("дата увольнения");
            entity.Property(e => e.i).HasComment("имя");
            entity.Property(e => e.int_num).HasComment("внутр. тел.");
            entity.Property(e => e.is_virtual).HasComment("признак виртуальности оператор");
            entity.Property(e => e.latitude).HasComment("Геолокация - широта");
            entity.Property(e => e.login).HasComment("логин");
            entity.Property(e => e.longitude).HasComment("Геолокация - долгота");
            entity.Property(e => e.mail_sign).HasComment("подпись");
            entity.Property(e => e.mob_num).HasComment("моб. тел.");
            entity.Property(e => e.o).HasComment("отчество");
            entity.Property(e => e.password).HasComment("пароль");
            entity.Property(e => e.password_change_dt).HasComment("дата последней смены пароля");
            entity.Property(e => e.position).HasComment("должность");
            entity.Property(e => e.prom_trans).HasComment("флаг \"перезакреплять при обеща");
            entity.Property(e => e.r_collection_plan_id).HasComment("ссылка на план сбора");
            entity.Property(e => e.r_department_id).HasComment("ссылка на подразделение (depar");
            entity.Property(e => e.r_role_id).HasComment("ссылка на роль");
            entity.Property(e => e.r_timetable_id).HasComment("ссылка на график");
            entity.Property(e => e.rank).HasComment("ранг");
            entity.Property(e => e.skill).HasComment("Квалификация пользователя (Словарь №237)");
            entity.Property(e => e.start_work_date).HasComment("дата выхода сотрудника в штат");
            entity.Property(e => e.win_user_name).HasComment("имя пользователя Windows");
            entity.Property(e => e.work_address).HasComment("рабочий адрес");
            entity.Property(e => e.work_num).HasComment("раб. тел.");
            entity.Property(e => e.work_zip_code).HasComment("индекс рабочего адреса");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<User> entity);
    }
}
