// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DatabaseContact.DatabaseContact.Configurations;
using DatabaseContact.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable enable

namespace DatabaseContact.DatabaseContact;

public partial class i_collectContext : DbContext
{
    public i_collectContext(DbContextOptions<i_collectContext> options)
        : base(options)
    {
    }

    public virtual DbSet<LawActPersonLink> LawActPersonLink { get; set; }

    public virtual DbSet<LawExecPersonLink> LawExecPersonLink { get; set; }

    public virtual DbSet<Models.Action> Action { get; set; }

    public virtual DbSet<Address> Address { get; set; }

    public virtual DbSet<ConstValue> ConstValue { get; set; }

    public virtual DbSet<Debt> Debt { get; set; }

    public virtual DbSet<Dict> Dict { get; set; }

    public virtual DbSet<DictName> DictName { get; set; }

    public virtual DbSet<DocAttach> DocAttach { get; set; }

    public virtual DbSet<DocLink> DocLink { get; set; }

    public virtual DbSet<LawAct> LawAct { get; set; }

    public virtual DbSet<LawActDscLog> LawActDscLog { get; set; }

    public virtual DbSet<LawActProtokol> LawActProtokol { get; set; }

    public virtual DbSet<LawExec> LawExec { get; set; }

    public virtual DbSet<LawExecDscLog> LawExecDscLog { get; set; }

    public virtual DbSet<LawExecProkokol> LawExecProkokol { get; set; }

    public virtual DbSet<Passport> Passport { get; set; }

    public virtual DbSet<Person> Person { get; set; }

    public virtual DbSet<Portfolio> Portfolio { get; set; }

    public virtual DbSet<User> User { get; set; }

    public virtual DbSet<WorkTask> WorkTask { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.LawActPersonLinkConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LawExecPersonLinkConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ActionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AddressConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ConstValueConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DebtConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DictConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DictNameConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DocAttachConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DocLinkConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LawActConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LawActDscLogConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LawActProtokolConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LawExecConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LawExecDscLogConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LawExecProtokolConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PassportConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PersonConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.PortfolioConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.UserConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.WorkTaskConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
