// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContact.Models;

[Keyless]
[Index("dt", Name = "IX_actions_dt")]
[Index("r_person_id", Name = "IX_actions_r_person_id")]
[Index("r_user_id", Name = "IX_actions_r_user_id")]
[Table("actions")]
public partial class Action
{
    public int id { get; set; }

    public int? r_user_id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? dt { get; set; }

    public int? module { get; set; }

    public int? typ { get; set; }

    [StringLength(64)]
    [Unicode(false)]
    public string? machine { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string? dsc { get; set; }

    public int? r_person_id { get; set; }

    [Column(TypeName = "numeric(10, 0)")]
    public decimal? duration { get; set; }

    [StringLength(16)]
    [Unicode(false)]
    public string? mod_version { get; set; }
}