// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContact.Models;

/// <summary>
/// информация об адресе должника
/// </summary>
[Index("block_flag", Name = "IX_address_block_flag")]
[Index("full_adr", Name = "IX_address_full_adr")]
[Index("parent_id", Name = "IX_address_parent_id")]
[Index("r_debt_guarantor_id", Name = "IX_address_r_debt_guarantor_id")]
[Index("r_person_property_id", Name = "IX_address_r_person_property_id")]
[Index("r_street_id", Name = "IX_address_r_street_id")]
[Index("typ", Name = "IX_address_typ")]
[Table("address")]
public partial class Address
{
    [Key]
    public int id { get; set; }

    /// <summary>
    /// ссылка на person
    /// </summary>
    public int? parent_id { get; set; }

    /// <summary>
    /// страна
    /// </summary>
    [StringLength(32)]
    [Unicode(false)]
    public string? country { get; set; }

    /// <summary>
    /// город
    /// </summary>
    [StringLength(64)]
    [Unicode(false)]
    public string? city { get; set; }

    /// <summary>
    /// индекс
    /// </summary>
    [StringLength(16)]
    [Unicode(false)]
    public string? index_code { get; set; }

    /// <summary>
    /// улица
    /// </summary>
    [StringLength(64)]
    [Unicode(false)]
    public string? street { get; set; }

    /// <summary>
    /// дом
    /// </summary>
    [StringLength(16)]
    [Unicode(false)]
    public string? house { get; set; }

    /// <summary>
    /// корпус
    /// </summary>
    [StringLength(16)]
    [Unicode(false)]
    public string? building { get; set; }

    /// <summary>
    /// квартира
    /// </summary>
    [StringLength(20)]
    [Unicode(false)]
    public string? flat { get; set; }

    /// <summary>
    /// тип (словарь №5)
    /// </summary>
    public int? typ { get; set; }

    /// <summary>
    /// комментарий
    /// </summary>
    [StringLength(128)]
    [Unicode(false)]
    public string? dsc { get; set; }

    /// <summary>
    /// признак &quot;блокировать&quot;
    /// </summary>
    public int? block_flag { get; set; }

    /// <summary>
    /// область
    /// </summary>
    [StringLength(64)]
    [Unicode(false)]
    public string? oblast { get; set; }

    /// <summary>
    /// район
    /// </summary>
    [StringLength(64)]
    [Unicode(false)]
    public string? district { get; set; }

    /// <summary>
    /// улица по справочнику
    /// </summary>
    public int? r_street_id { get; set; }

    /// <summary>
    /// ссылка на KLADR
    /// </summary>
    [StringLength(13)]
    [Unicode(false)]
    public string? r_kladr_id { get; set; }

    /// <summary>
    /// 1-необходим выезд, 2-подготовл
    /// </summary>
    public int? visit_state { get; set; }

    /// <summary>
    /// полный текст адреса
    /// </summary>
    [StringLength(256)]
    [Unicode(false)]
    public string? full_adr { get; set; }

    /// <summary>
    /// ID в главной БД
    /// </summary>
    [Column("id$")]
    public int? id_ { get; set; }

    /// <summary>
    /// дата загрузки адреса
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? load_dt { get; set; }

    /// <summary>
    /// статус (словарь №63)
    /// </summary>
    public int? status { get; set; }

    /// <summary>
    /// дата последнего выезда
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? last_dt { get; set; }

    /// <summary>
    /// признак возвращенного письма
    /// </summary>
    public int? is_returned { get; set; }

    /// <summary>
    /// статус адреса (словарь № 72)
    /// </summary>
    public int? dataq_state { get; set; }

    /// <summary>
    /// флаг проживает
    /// </summary>
    public int? is_residence { get; set; }

    /// <summary>
    /// дата, когда необходимо сделать
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? visit_time { get; set; }

    /// <summary>
    /// ссылка на debt_guarantor
    /// </summary>
    public int? r_debt_guarantor_id { get; set; }

    /// <summary>
    /// ссылка на person_property
    /// </summary>
    public int? r_person_property_id { get; set; }

    /// <summary>
    /// признак, что адрес загружен ст
    /// </summary>
    public int? text_flag { get; set; }

    /// <summary>
    /// окато
    /// </summary>
    [StringLength(11)]
    [Unicode(false)]
    public string? okato { get; set; }

    /// <summary>
    /// дата изменения
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? modify_dt { get; set; }

    /// <summary>
    /// полный код KLADR (17 символов)
    /// </summary>
    [StringLength(17)]
    [Unicode(false)]
    public string? r_kladr_street_id { get; set; }

    /// <summary>
    /// дата верификации адреса
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? verification_dt { get; set; }

    /// <summary>
    /// используется в ETL
    /// </summary>
    [Column("EXT_ID$")]
    [StringLength(32)]
    [Unicode(false)]
    public string? EXT_ID_ { get; set; }

    /// <summary>
    /// дата блокировки
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? BLOCK_DT { get; set; }

    /// <summary>
    /// причина блокировки (словарь 314)
    /// </summary>
    public int? BLOCK_REASON { get; set; }

    /// <summary>
    /// Код ФИАС
    /// </summary>
    [StringLength(40)]
    public string? FIAS_CODE { get; set; }

    /// <summary>
    /// Словарный атрибут адреса 1. Ссылка на словарь 372
    /// </summary>
    public int? DICT_VALUE_1 { get; set; }

    /// <summary>
    /// Словарный атрибут адреса 2. Ссылка на словарь 373
    /// </summary>
    public int? DICT_VALUE_2 { get; set; }

    /// <summary>
    /// Словарный атрибут адреса 3. Ссылка на словарь 374
    /// </summary>
    public int? DICT_VALUE_3 { get; set; }

    /// <summary>
    /// ID пользователя, который добавил запись
    /// </summary>
    public int? R_USER_ID { get; set; }
}