// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContact.Models;

/// <summary>
/// информация о поручителе по долгу
/// </summary>
[Index("parent_id", Name = "IX_D_GUARANTOR_PARENT_ID")]
public partial class DebtGuarantor
{
    [Key]
    public int id { get; set; }

    /// <summary>
    /// ссылка на debt
    /// </summary>
    public int? parent_id { get; set; }
    [ForeignKey(nameof(parent_id))]
    public virtual Debt Debt { get; set; }

    /// <summary>
    /// залоговая стоимость
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? sum { get; set; }

    /// <summary>
    /// комментарий
    /// </summary>
    [StringLength(512)]
    [Unicode(false)]
    public string? dsc { get; set; }

    /// <summary>
    /// ФИО
    /// </summary>
    [StringLength(1024)]
    [Unicode(false)]
    public string? fio { get; set; }

    /// <summary>
    /// Дата рождения
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? birth_date { get; set; }

    /// <summary>
    /// паспорт
    /// </summary>
    [StringLength(1024)]
    [Unicode(false)]
    public string? passport { get; set; }

    /// <summary>
    /// адрес
    /// </summary>
    [StringLength(256)]
    [Unicode(false)]
    public string? address { get; set; }

    /// <summary>
    /// тип должника (словарь №54)
    /// </summary>
    public int? typ { get; set; }

    /// <summary>
    /// ID АБС
    /// </summary>
    [StringLength(32)]
    [Unicode(false)]
    public string? ext_id { get; set; }

    /// <summary>
    /// пол
    /// </summary>
    [StringLength(1)]
    [Unicode(false)]
    public string? sex { get; set; }

    /// <summary>
    /// семейное положение (словарь №1
    /// </summary>
    public int? family_status { get; set; }

    /// <summary>
    /// образование (словарь №38)
    /// </summary>
    public int? education { get; set; }

    /// <summary>
    /// название компании
    /// </summary>
    [StringLength(64)]
    [Unicode(false)]
    public string? company_name { get; set; }

    /// <summary>
    /// должность
    /// </summary>
    [StringLength(64)]
    [Unicode(false)]
    public string? position { get; set; }

    /// <summary>
    /// ИНН
    /// </summary>
    [StringLength(16)]
    [Unicode(false)]
    public string? inn { get; set; }

    /// <summary>
    /// Код причины постановки (КПП)
    /// </summary>
    [StringLength(16)]
    [Unicode(false)]
    public string? kpp { get; set; }

    /// <summary>
    /// Платежные реквизиты (юр. лица)
    /// </summary>
    [StringLength(256)]
    [Unicode(false)]
    public string? pay_info { get; set; }

    /// <summary>
    /// ФИО ген. директора (юр. лица)
    /// </summary>
    [StringLength(32)]
    [Unicode(false)]
    public string? director_fio { get; set; }

    /// <summary>
    /// номер договора
    /// </summary>
    [StringLength(32)]
    [Unicode(false)]
    public string? contract { get; set; }

    /// <summary>
    /// дата заключения
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? start_date { get; set; }

    /// <summary>
    /// дата окончания
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? end_date { get; set; }

    /// <summary>
    /// дата завершения
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? finish_date { get; set; }

    /// <summary>
    /// валюта
    /// </summary>
    public int? currency { get; set; }

    /// <summary>
    /// рыночная стоимость
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? real_sum { get; set; }

    /// <summary>
    /// справедливая стоимость
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? fair_sum { get; set; }

    /// <summary>
    /// Коэффициент категории качества
    /// </summary>
    public float? quality_coeff { get; set; }

    /// <summary>
    /// наименование объекта
    /// </summary>
    [StringLength(256)]
    [Unicode(false)]
    public string? name { get; set; }

    /// <summary>
    /// место рождения
    /// </summary>
    [StringLength(256)]
    [Unicode(false)]
    public string? birth_place { get; set; }

    /// <summary>
    /// Тип ответственности (Словарь №
    /// </summary>
    public int? liability { get; set; }

    /// <summary>
    /// Удостоверение личности
    /// </summary>
    [StringLength(16)]
    [Unicode(false)]
    public string? id_card { get; set; }

    /// <summary>
    /// Бизнес-идентификационный номер
    /// </summary>
    [StringLength(16)]
    [Unicode(false)]
    public string? social_number { get; set; }

    /// <summary>
    /// Регистрационный номер налогопл
    /// </summary>
    [StringLength(16)]
    [Unicode(false)]
    public string? tin { get; set; }

    public int? kind { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string? string_value_1 { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string? string_value_2 { get; set; }

    [Column(TypeName = "money")]
    public decimal? number_value_1 { get; set; }

    /// <summary>
    /// БИК
    /// </summary>
    [StringLength(16)]
    [Unicode(false)]
    public string? BIK { get; set; }

    /// <summary>
    /// Банк
    /// </summary>
    [StringLength(160)]
    [Unicode(false)]
    public string? B_NAME { get; set; }

    /// <summary>
    /// Ссылка на словарь 1 (словарь №261)
    /// </summary>
    public int? DICT_VALUE_1 { get; set; }

    /// <summary>
    /// Кор. Счет
    /// </summary>
    [StringLength(32)]
    [Unicode(false)]
    public string? K_ACCOUNT { get; set; }

    /// <summary>
    /// ОГРН
    /// </summary>
    [StringLength(16)]
    [Unicode(false)]
    public string? OGRN { get; set; }

    /// <summary>
    /// ОКПО
    /// </summary>
    [StringLength(10)]
    [Unicode(false)]
    public string? OKPO { get; set; }

    /// <summary>
    /// ОКВЕД
    /// </summary>
    [StringLength(16)]
    [Unicode(false)]
    public string? OKVED { get; set; }

    /// <summary>
    /// Расчетный счет
    /// </summary>
    [StringLength(32)]
    [Unicode(false)]
    public string? R_ACCOUNT { get; set; }

    /// <summary>
    /// Тип удост. документа (код по словарю №335)
    /// </summary>
    public int? PAS_DOC_TYPE { get; set; }

    /// <summary>
    /// Номер паспорта
    /// </summary>
    [StringLength(120)]
    public string? PAS_NUMBER { get; set; }

    /// <summary>
    /// Место выдачи
    /// </summary>
    [StringLength(256)]
    public string? PAS_PLACE { get; set; }

    /// <summary>
    /// Серия паспорта
    /// </summary>
    [StringLength(80)]
    public string? PAS_SERIES { get; set; }

    /// <summary>
    /// Дата выдачи
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? PASS_DT { get; set; }
}