// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;


namespace DatabaseContact.Models;


[Index("calc_date", Name = "IX_debt_calc_calc_date")]
[Index("is_cancel", Name = "IX_debt_calc_is_cancel")]
[Index("is_confirmed", Name = "IX_debt_calc_is_confirmed")]
[Index("r_promise_id", Name = "IX_debt_calc_r_promise_id")]
[Table("debt_calc")]
public partial class DebtCalc
{
    [Key]
    public int id { get; set; }

    public int? parent_id { get; set; }

    [Column(TypeName = "money")]
    public decimal? sum { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? dt { get; set; }

    public int? is_confirmed { get; set; }

    public int? is_cancel { get; set; }

    public int? r_promise_id { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string? dsc { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? calc_date { get; set; }

    public int? r_currency_id { get; set; }

    [Column(TypeName = "money")]
    public decimal? int_sum { get; set; }

    [Column(TypeName = "money")]
    public decimal? commission { get; set; }

    [Column("id$")]
    public int? id_ { get; set; }

    public int? r_user_id { get; set; }

    public int? req_change { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? report_date { get; set; }

    public int? typ { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? confirm_dt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? cancel_dt { get; set; }

    public int? invoice_flag { get; set; }

    public int? r_req_user_id { get; set; }

    public int? r_bank_requisites_id { get; set; }

    [StringLength(64)]
    public string? ext_id { get; set; }

    [Column("$id$")]
    public int? _id_ { get; set; }

    [StringLength(64)]
    [Unicode(false)]
    public string? payer_name { get; set; }

    [StringLength(32)]
    [Unicode(false)]
    public string? contract_number { get; set; }

    [StringLength(32)]
    [Unicode(false)]
    public string? ticket_number { get; set; }

    public int? purpose { get; set; }

    /// <summary>
    /// Дополнительный параметр число
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? NUMBER_VALUE_1 { get; set; }

    /// <summary>
    /// Дополнительный параметр число
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? NUMBER_VALUE_2 { get; set; }

    /// <summary>
    /// Дополнительный параметр число
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? NUMBER_VALUE_3 { get; set; }

    /// <summary>
    /// Дополнительный параметр число
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? NUMBER_VALUE_4 { get; set; }
}

