// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContact.Models;

/// <summary>
/// словарные термины
/// </summary>
[Index("parent_id", "code", Name = "IX_DICT_PARENT_ID&CODE")]
[Table("dict")]
public partial class Dict
{
    [Key]
    public int id { get; set; }

    /// <summary>
    /// ссылка на code описателя слова
    /// </summary>
    public int parent_id { get; set; }

    /// <summary>
    /// код термина
    /// </summary>
    public int code { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string? name { get; set; }

    /// <summary>
    /// ссылка на термин родительского
    /// </summary>
    public int? r_code { get; set; }

    /// <summary>
    /// 1 - системный, 2 - общий
    /// </summary>
    public int? typ { get; set; }

    /// <summary>
    /// дата изменения записи
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? change_dt { get; set; }

    public int? is_close { get; set; }

    public int? KIND { get; set; }

    /// <summary>
    /// язык (словарь 78)
    /// </summary>
    public int? LANG { get; set; }

    public int? lang_canonical { get; set; }

    /// <summary>
    /// Внешний код
    /// </summary>
    [StringLength(64)]
    public string? EXT_ID { get; set; }
    [ForeignKey(nameof(parent_id))]
    [InverseProperty(nameof(DictName.dict))]
    public virtual DictName parent { get; set; } = null!;
}
