// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContact.Models;

/// <summary>
/// описатель словаря
/// </summary>
[Table("dict_name")]
public partial class DictName
{
    public int id { get; set; }

    /// <summary>
    /// номер словаря
    /// </summary>
    [Key]
    public int code { get; set; }

    [StringLength(64)]
    [Unicode(false)]
    public string? name { get; set; }

    /// <summary>
    /// код родительского словаря
    /// </summary>
    public int? r_code { get; set; }

    /// <summary>
    /// 1 - системный, 2 - общий
    /// </summary>
    public int? typ { get; set; }

    public int? KIND { get; set; }

    /// <summary>
    /// признак отсутствия использования словаря у Клиента. 1 – словарь не используется. Иначе – используется
    /// </summary>
    public int? NOT_USE { get; set; }

    /// <summary>
    /// название на альтернативном языке
    /// </summary>
    [StringLength(64)]
    public string? NAME2 { get; set; }
    [InverseProperty(nameof(Dict.parent))]
    public virtual List<Dict> dict { get; set; } = new();
}
