// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContact.Models;
[Table("doc_attach")]
public partial class DocAttach
{
    [Key]
    public int id { get; set; }

    /// <summary>
    /// ссылка table_spec
    /// </summary>
    public int obj_id { get; set; }

    /// <summary>
    /// ссылка на запись
    /// </summary>
    public int r_id { get; set; }

    /// <summary>
    /// имя документа
    /// </summary>
    [StringLength(255)]
    [Unicode(false)]
    public string? name { get; set; }

    /// <summary>
    /// имя файла
    /// </summary>
    [StringLength(255)]
    [Unicode(false)]
    public string? filename { get; set; }

    /// <summary>
    /// файл
    /// </summary>
    [Column(TypeName = "image")]
    public byte[]? filebody { get; set; }

    /// <summary>
    /// версия
    /// </summary>
    public int? vers1 { get; set; }

    /// <summary>
    /// версия
    /// </summary>
    public int? vers2 { get; set; }

    /// <summary>
    /// является ли активным
    /// </summary>
    public int? is_active { get; set; }

    /// <summary>
    /// словарь №100
    /// </summary>
    public int? attach_typ { get; set; }

    public int? r_user_id { get; set; }

    [ForeignKey(nameof(r_user_id))]
    [InverseProperty(nameof(Models.User.DocAttaches))]
    public virtual User? User { get; set; }

    /// <summary>
    /// дата
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? dt { get; set; }

    /// <summary>
    /// номер
    /// </summary>
    [StringLength(32)]
    [Unicode(false)]
    public string? number { get; set; }

    /// <summary>
    /// наименование файла на сервере 
    /// </summary>
    [StringLength(600)]
    public string? FILE_SERVER_NAME { get; set; }

    /// <summary>
    /// относительный путь к файлу на  на сервере (например, 000/001)
    /// </summary>
    [StringLength(600)]
    public string? REL_SERVER_PATH { get; set; }

    /// <summary>
    /// источник возникновения документа (ссылка на table_spec)
    /// </summary>
    public int? ORIGIN_OBJ { get; set; }

    /// <summary>
    /// ссылка на запись в источнике
    /// </summary>
    public int? R_ORIGIN_ID { get; set; }

    /// <summary>
    /// дата последнего изменения
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? CHANGE_DT { get; set; }

    /// <summary>
    /// размер файла
    /// </summary>
    public int? DOC_SIZE { get; set; }

    /// <summary>
    /// Режим хранения файла (1 – в БД, 2 – в директории на сервере, 3 – другое (клиентский вариант))
    /// </summary>
    public int? SAVE_MODE { get; set; }

    /// <summary>
    /// Расширение файла
    /// </summary>
    [StringLength(50)]
    public string? EXTENSION { get; set; }

    /// <summary>
    /// Идентификатор во внешней системе
    /// </summary>
    [StringLength(32)]
    public string? EXT_ID { get; set; }

    /// <summary>
    /// Дата начала действия
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? FROM_DT { get; set; }

    /// <summary>
    /// Дата окончания действия
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? TO_DT { get; set; }

    /// <summary>
    /// Техническое поле типа словарь 1
    /// </summary>
    public int? DICT_VALUE_1 { get; set; }

    /// <summary>
    /// Техническое поле типа дата 1
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DT_VALUE_1 { get; set; }

    /// <summary>
    /// Ссылка на папку
    /// </summary>
    public int? R_FOLDER_ID { get; set; }

    /// <summary>
    /// Комментарий
    /// </summary>
    [StringLength(512)]
    public string? DSC { get; set; }
}