// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContact.Models;
[Table("law_act_solicitation")]

public partial class LawActSolicitation
{
    [Key]
    public int id { get; set; }


    public int? parent_id { get; set; }

    [ForeignKey(nameof(parent_id))]
    [InverseProperty(nameof(Models.LawAct.LawActSolicitations))]
    public virtual LawAct? LawAct { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? start_date { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? end_date { get; set; }

    public int? typ { get; set; }

    public int? status { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string? dsc { get; set; }

    /// <summary>
    /// Название гос.органа
    /// </summary>
    [StringLength(128)]
    public string? STATE_ORGAN_NAME { get; set; }

    /// <summary>
    /// Адрес гос.органа
    /// </summary>
    [StringLength(128)]
    public string? STATE_ORGAN_ADDRESS { get; set; }

    /// <summary>
    /// Причина по словарю 344
    /// </summary>
    public int? REASON_CODE { get; set; }

    /// <summary>
    /// Реквизиты гос.органа
    /// </summary>
    [StringLength(512)]
    public string? STATE_ORGAN_REQUISITES { get; set; }

    /// <summary>
    /// Запрошенная сумма
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? REQUEST_SUM { get; set; }

    /// <summary>
    /// Полученная сумма
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? RESULT_SUM { get; set; }
}
