// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContact.Models;

[Index("parent_id", Name = "IX_law_act_dsc_log_parent_id")]
[Table("law_act_dsc_log")]
public partial class LawActDscLog
{
    [Key]
    public int id { get; set; }

    public int? parent_id { get; set; }

    [ForeignKey(nameof(parent_id))]
    [InverseProperty(nameof(Models.LawAct.LawActDscLogs))]
    public virtual LawAct? LawAct { get; set; }

    public int? law_typ { get; set; }

    /// <summary>
    /// комментарий
    /// </summary>
    [StringLength(4000)]
    [Unicode(false)]
    public string? dsc { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? dt { get; set; }

    public int? r_user_id { get; set; }

    [ForeignKey(nameof(r_user_id))]
    [InverseProperty(nameof(Models.User.LawActDscLogs))]
    public virtual User? User { get; set; }
}