// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContact.Models;

[Index("parent_id", Name = "IX_law_exec_dsc_log_parent_id")]
[Table("law_exec_dsc_log")]
public partial class LawExecDscLog
{
    [Key]
    public int id { get; set; }

    public int? parent_id { get; set; }

    [StringLength(4000)]
    [Unicode(false)]
    public string? dsc { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? dt { get; set; }

    public int? r_user_id { get; set; }
}