// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using DatabaseContact.Models;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContact.Models;

/// <summary>
/// информация об исполнительном п
/// </summary>
[Index("r_act_id", Name = "IX_LAW_EXEC_R_ACT_ID")]
[Index("r_person_id", Name = "IX_LAW_EXEC_R_PERSON_ID")]
[Index("r_user_id", Name = "IX_LAW_EXEC_R_USER_ID")]
[Index("r_debt_id", Name = "IX_law_exec_r_debt_id")]
[Table("law_exec")]
public partial class LawExec
{
    [Key]
    public int id { get; set; }

    /// <summary>
    /// ссылка на person
    /// </summary>
    public int? r_person_id { get; set; }

    /// <summary>
    /// ссылка на debt
    /// </summary>
    public int? r_debt_id { get; set; }

    /// <summary>
    /// ссылка на portfolio
    /// </summary>
    public int? r_portfolio_id { get; set; }

    /// <summary>
    /// общая сумма долга
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? total_sum { get; set; }

    /// <summary>
    /// ссылка на users
    /// </summary>
    public int? r_user_id { get; set; }

    /// <summary>
    /// номер исполнительного документ
    /// </summary>
    [StringLength(32)]
    [Unicode(false)]
    public string? court_doc_num { get; set; }

    /// <summary>
    /// название суда (устар.)(не испо
    /// </summary>
    [StringLength(256)]
    public string? court_name { get; set; }

    /// <summary>
    /// дата вынесения
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? court_date { get; set; }

    /// <summary>
    /// название ФССП (устар.)(не испо
    /// </summary>
    [StringLength(64)]
    [Unicode(false)]
    public string? fssp_name { get; set; }

    /// <summary>
    /// номер исполнительного производ
    /// </summary>
    [StringLength(64)]
    [Unicode(false)]
    public string? fssp_doc_num { get; set; }

    /// <summary>
    /// дата сдачи в ФССП
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? fssp_date { get; set; }

    /// <summary>
    /// дата возбуждения ИП
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? start_date { get; set; }

    /// <summary>
    /// наличие залогового имущества
    /// </summary>
    public int? deposit_typ { get; set; }

    /// <summary>
    /// ФИО пристава (не используется)
    /// </summary>
    [StringLength(32)]
    [Unicode(false)]
    public string? officer_fio { get; set; }

    /// <summary>
    /// телефон пристава (не используе
    /// </summary>
    [StringLength(32)]
    [Unicode(false)]
    public string? officer_phone { get; set; }

    /// <summary>
    /// комната пристава (не используе
    /// </summary>
    [StringLength(8)]
    [Unicode(false)]
    public string? officer_room { get; set; }

    /// <summary>
    /// ФИО пристава (зам.) (не исполь
    /// </summary>
    [StringLength(32)]
    [Unicode(false)]
    public string? officer_fio2 { get; set; }

    /// <summary>
    /// телефон пристава (зам.) (не ис
    /// </summary>
    [StringLength(32)]
    [Unicode(false)]
    public string? officer_phone2 { get; set; }

    /// <summary>
    /// комната пристава (зам.) (не ис
    /// </summary>
    [StringLength(8)]
    [Unicode(false)]
    public string? officer_room2 { get; set; }

    /// <summary>
    /// статус (устар.) (не использует
    /// </summary>
    [StringLength(4)]
    [Unicode(false)]
    public string? status { get; set; }

    /// <summary>
    /// дата окончания производства
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? finish_date { get; set; }

    /// <summary>
    /// причина окончания производства
    /// </summary>
    public int? finish_reason { get; set; }

    /// <summary>
    /// комментарий
    /// </summary>
    [StringLength(4000)]
    [Unicode(false)]
    public string? dsc { get; set; }

    /// <summary>
    /// указания руководителя
    /// </summary>
    [StringLength(512)]
    [Unicode(false)]
    public string? instruct { get; set; }

    /// <summary>
    /// ссылка на law_court (ФССП)
    /// </summary>
    public int? r_court_id { get; set; }

    /// <summary>
    /// ссылка на law_act
    /// </summary>
    public int? r_act_id { get; set; }

    /// <summary>
    /// статус (словарь №77)
    /// </summary>
    public int? state { get; set; }

    /// <summary>
    /// номер договора
    /// </summary>
    [StringLength(128)]
    [Unicode(false)]
    public string? contract { get; set; }

    /// <summary>
    /// валюта
    /// </summary>
    public int? currency { get; set; }

    /// <summary>
    /// цвет
    /// </summary>
    public int? int_color { get; set; }

    /// <summary>
    /// название продукта
    /// </summary>
    [StringLength(256)]
    public string? name { get; set; }

    /// <summary>
    /// тип продукта (ссылка на словар
    /// </summary>
    public int? typ_name { get; set; }

    /// <summary>
    /// гос. пошлина
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? due_sum { get; set; }

    /// <summary>
    /// акт о завершении
    /// </summary>
    [StringLength(64)]
    [Unicode(false)]
    public string? uncollectibility_act { get; set; }

    /// <summary>
    /// дата загрузки\формирования ИП
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? load_dt { get; set; }

    /// <summary>
    /// дата получения исп.листа
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? receipt_act_dt { get; set; }

    /// <summary>
    /// Тип исполнительного документа 
    /// </summary>
    public int? executive_typ { get; set; }

    /// <summary>
    /// Дата вступления решения суда в
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? entry_force_dt { get; set; }

    /// <summary>
    /// Причина отказа (Словарь №125)
    /// </summary>
    public int? reject_reason { get; set; }

    /// <summary>
    /// Дата отказа
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? reject_date { get; set; }

    /// <summary>
    /// Дата получения постановления о
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? complete_date { get; set; }

    /// <summary>
    /// дата получения ИП на арест
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? receipt_arrest_dt { get; set; }

    /// <summary>
    /// дата получения ИП на взыскание
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? receipt_recover_dt { get; set; }

    /// <summary>
    /// сумма мирового соглашения
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? settlement_sum { get; set; }

    /// <summary>
    /// дата мирового соглашения
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? settlement_date { get; set; }

    /// <summary>
    /// плановая дата подачи в ФССП
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? fssp_plan_date { get; set; }

    /// <summary>
    /// плановая дата окончания ИП
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? complete_plan_date { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? restriction_to_leave_dt { get; set; }

    /// <summary>
    /// Примечание ИП (Словарь №248)
    /// </summary>
    public int? dict_value_1 { get; set; }

    /// <summary>
    /// адрес, по которому на должника
    /// </summary>
    public int? r_address_id { get; set; }

    [Column("ext_id$")]
    [StringLength(32)]
    [Unicode(false)]
    public string? ext_id_ { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DT_TO_ARCHIVE { get; set; }

    /// <summary>
    /// Дата приостановления ИП
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? PAUSE_DATE { get; set; }

    /// <summary>
    /// Причина приостановления (словарь №266)
    /// </summary>
    public int? PAUSE_REASON { get; set; }

    /// <summary>
    /// остаток по ИД
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? REST_SUM { get; set; }

    /// <summary>
    /// Способ подачи по словарю №16
    /// </summary>
    public int? DELIVERY_TYP { get; set; }

    /// <summary>
    /// id запроса в Кворум
    /// </summary>
    public int? QUORUM_ID { get; set; }

    /// <summary>
    /// Дата обжалования
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? APPEAL_DATE { get; set; }

    /// <summary>
    /// Техническое поле типа дата 1
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? DT_VALUE_1 { get; set; }
}
