// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContact.Models;
[Table("passport")]
public partial class Passport
{
    [Key]
    public int id { get; set; }

    [StringLength(80)]
    [Unicode(false)]
    public string? series { get; set; }

    [StringLength(120)]
    [Unicode(false)]
    public string? number { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? dt { get; set; }

    [StringLength(512)]
    [Unicode(false)]
    public string? place { get; set; }

    [Column("id$")]
    public int? id_ { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? load_dt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? end_dt { get; set; }

    [StringLength(8)]
    [Unicode(false)]
    public string? depart_code { get; set; }

    public int? R_PROSECUTION_PERSON_ID { get; set; }

    /// <summary>
    /// используется в ETL
    /// </summary>
    [Column("EXT_ID$")]
    [StringLength(64)]
    public string? EXT_ID_ { get; set; }

    /// <summary>
    /// Тип документа, удостоверяющего личность (Словарь 335)
    /// </summary>
    public int? DOC_TYPE { get; set; }
}