// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContact.Models;

/// <summary>
/// информация о портфеле
/// </summary>
[Index("parent_id", Name = "IX_portfolio_parent_id")]
[Table("portfolio")]
public partial class Portfolio
{
    [Key]
    public int id { get; set; }

    /// <summary>
    /// ссылка на банк
    /// </summary>
    public int? parent_id { get; set; }

    /// <summary>
    /// название портфеля
    /// </summary>
    [StringLength(64)]
    [Unicode(false)]
    public string? name { get; set; }

    /// <summary>
    /// дата подписания
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? sign_date { get; set; }

    /// <summary>
    /// дата окончания
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? end_date { get; set; }

    /// <summary>
    /// коэффициент успешности
    /// </summary>
    public float? success_coeff { get; set; }

    /// <summary>
    /// код группы
    /// </summary>
    public int? group_index { get; set; }

    /// <summary>
    /// ссылка на формулу (для комисси
    /// </summary>
    public int? r_formula_id { get; set; }

    /// <summary>
    /// комментарий
    /// </summary>
    [StringLength(128)]
    [Unicode(false)]
    public string? dsc { get; set; }

    /// <summary>
    /// информация о договоре с банком
    /// </summary>
    [StringLength(64)]
    public string? contract_info { get; set; }

    /// <summary>
    /// ID в главной БД
    /// </summary>
    [Column("id$")]
    public int? id_ { get; set; }

    /// <summary>
    /// ссылка на package
    /// </summary>
    public int? r_package_id { get; set; }

    /// <summary>
    /// статус (словарь №57)
    /// </summary>
    public int? status { get; set; }

    /// <summary>
    /// номер портфеля
    /// </summary>
    public int? code { get; set; }

    /// <summary>
    /// тип портфеля (словарь №58)
    /// </summary>
    public int? typ { get; set; }

    /// <summary>
    /// тип долгов портфеля (словарь №
    /// </summary>
    public int? debt_typ { get; set; }

    /// <summary>
    /// номер раздела портфеля
    /// </summary>
    public int? code2 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? load_dt { get; set; }

    /// <summary>
    /// ссылка на portfolio_calc_rule
    /// </summary>
    public int? r_calc_rule_id { get; set; }

    /// <summary>
    /// дата начала работ
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? real_load_dt { get; set; }

    /// <summary>
    /// ссылка правило расчета комисси
    /// </summary>
    public int? r_com_rule_id { get; set; }

    /// <summary>
    /// приоритет
    /// </summary>
    public int? prior { get; set; }

    /// <summary>
    /// предусмотрен legal
    /// </summary>
    public int? provided_legal { get; set; }

    /// <summary>
    /// Вид деятельности (словарь №104
    /// </summary>
    public int? sector { get; set; }

    /// <summary>
    /// Классификация (Подразделение) 
    /// </summary>
    public int? grade { get; set; }

    /// <summary>
    /// Тип договора (Цессия\Агентский
    /// </summary>
    public int? contract_typ { get; set; }

    /// <summary>
    /// агрессивный план
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? aggressive_plan { get; set; }

    /// <summary>
    /// целевой план
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? objective_plan { get; set; }

    /// <summary>
    /// стоимость покупки
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? purchase_price { get; set; }

    /// <summary>
    /// прогноз взыскания
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? forecast { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? last_pay_date { get; set; }

    /// <summary>
    /// окончание даты учета платежеа 
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? payments_until_dt { get; set; }

    /// <summary>
    /// Направление портфеля словарь D
    /// </summary>
    public int? Direction { get; set; }

    /// <summary>
    /// период, после которого операто
    /// </summary>
    public int? auto_fix_period { get; set; }

    /// <summary>
    /// Оператор по умолчанию для порт
    /// </summary>
    public int? auto_user_id { get; set; }

    /// <summary>
    /// стоимость продажи
    /// </summary>
    [Column(TypeName = "money")]
    public decimal? sale_price { get; set; }
}