// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DatabaseContact.Models;

/// <summary>
/// связь долга и оператора (соотн
/// </summary>
[Index("r_debt_id", "call_time", Name = "IX_WORK_TASK_CALL_TIME&R_DEBT_ID")]
[Index("r_debt_id", "office_time", Name = "IX_WORK_TASK_OFFICE_TIME&R_DEBT_ID")]
[Index("r_user_id", Name = "IX_work_task_r_user_id")]
[Table("work_task")]
public partial class WorkTask
{
    [Key]
    public int id { get; set; }

    /// <summary>
    /// ссылка на долг
    /// </summary>
    public int? r_debt_id { get; set; }

    [ForeignKey(nameof(r_debt_id))]
    [InverseProperty(nameof(Models.Debt.WorkTask))]
    public virtual Debt? Debt { get; set; }

    /// <summary>
    /// ссылка на оператора (users.id)
    /// </summary>
    public int? r_user_id { get; set; }

    [ForeignKey(nameof(r_user_id))]
    [InverseProperty(nameof(Models.User.WorkTasks))]
    public virtual User? User { get; set; }

    /// <summary>
    /// приоритет (чем меньше тем выше
    /// </summary>
    public int? prior { get; set; }

    /// <summary>
    /// дата и время для звонка должни
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? call_time { get; set; }

    /// <summary>
    /// пользователь, который своим де
    /// </summary>
    public int? r_admin_id { get; set; }

    /// <summary>
    /// см. расшифровку внизу
    /// </summary>
    public int? r_contact_id { get; set; }

    public int? reason { get; set; }

    /// <summary>
    /// дата начала работы с должником
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? start_work_date { get; set; }

    /// <summary>
    /// дата завершения работы с должн
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? finish_work_date { get; set; }

    /// <summary>
    /// причина перевода в hard (слова
    /// </summary>
    public int? reason_soft { get; set; }

    /// <summary>
    /// причина перевода в legal (слов
    /// </summary>
    public int? reason_hard { get; set; }

    /// <summary>
    /// дата посещение офиса
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? office_time { get; set; }

    /// <summary>
    /// ссылка на оператора (users.id)
    /// </summary>
    public int? r_user_id_h { get; set; }

    /// <summary>
    /// ссылка на оператора (users.id)
    /// </summary>
    public int? r_user_id_l { get; set; }

    /// <summary>
    /// Плановая дата завершения работы с должником
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? PLAN_FINISH_WORK_DATE { get; set; }

    [ForeignKey("r_user_id_h")]
    [InverseProperty("work_taskr_user_id_hNavigation")]
    public virtual User? r_user_id_hNavigation { get; set; }

    [ForeignKey("r_user_id_l")]
    [InverseProperty("work_taskr_user_id_lNavigation")]
    public virtual User? r_user_id_lNavigation { get; set; }
}